### PR TITLE
fix: update extract_proteins with new Uniprot API

### LINKED ISSUE #4: Uniprot API update
The API was apparently changed, causing extract_proteins() to break. Looking into fixes

### PR DESCRIPTION
**Pull request by carrascomj**
Closes #4 

The fix is not super nice, since it does the chunking manually instead of using Uniprot's pagination but it is functional.

### CODE REVIEW

**Comment by carrascomj** [comment]
requests has to be downgraded for the tests to pass in python < 3.9.

@cplong90 Let me know if you have a better fix or you would prefer to have this merged!

**Comment by cplong90** [comment]
hey I got something working in notebook here that gets the prot sequence from uniprot and then calculates the MW using biopython. Let me know if you think this is better or worse, no strong feelings. Maybe the sequence winds of being handy?

```
`UNIPROT_PATTERN = re.compile(
    r"(?:prot_)?([OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2})"
)
key_fn=lambda x: UNIPROT_PATTERN.match(x.id)[1]

def _get_all_proteins(model: Model, key_fn) -> Dict:
    """Generate a set of dict of Uniprot ID: reaction id from a `model`."""
    return {key_fn(prot): prot.id for prot in model.proteins}

all_proteins = _get_all_proteins(model, key_fn)

df_prot = pd.DataFrame(
        {
            "uniprot": list(all_proteins.keys()),
            "reactions": list(all_proteins.values()),
        }
    )

import zipfile
import gzip
import io
import time

import requests
import pandas
import tqdm


def download_uniprot_beta_data(accessions, fields):
    
    # IF TOO MANY ACCESSIONS, RUN IN BATCHES
    # That's because running batches too big triggers errors.
    BATCH_SIZE = 2000
    if len(accessions) > BATCH_SIZE:
        accessions_batches = [
            accessions[i:i+BATCH_SIZE]
            for i in range(0, len(accessions), BATCH_SIZE)
        ]
        subdfs = [
            download_uniprot_beta_data(batch, fields)
            for batch in tqdm.tqdm(accessions_batches)
        ]
        return pandas.concat(subdfs, ignore_index=True)
    
    # SUBMIT THE QUERY

    data = {"ids": accessions, "from": "UniProtKB_AC-ID", "to": "UniProtKB"}
    job_submission_query = requests.post("https://rest.uniprot.org/idmapping/run", data=data)
    job_id = job_submission_query.json()["jobId"]

    # POLL FOR STATUS
    endpoint = f"https://rest.uniprot.org/idmapping/status/{job_id}"
    while True:
        job_status_query = requests.get(endpoint)
        job_status = job_status_query.json()
        if "results" in job_status:
            break
        time.sleep(3)

    # GET THE RESULTS, PARSE THEM INTO A DATAFRAME
    endpoint = f"https://rest.uniprot.org/idmapping/uniprotkb/results/stream/{job_id}"
    response = requests.get(
        endpoint,
        params={
            "compressed": 'true',
            "download": 'true',
            "fields": ",".join(fields),
            "format":"tsv"
        }
    )
    gzip_reader = gzip.GzipFile(fileobj=io.BytesIO(response.content))
    return pandas.read_csv(gzip_reader, sep="\t")

dfseqs = download_uniprot_beta_data(
    accessions=list(df['uniprot']),
    fields = [
        "sequence"
    ]
)

df_prot = df_prot.merge(dfseqs, how='outer',left_on ='uniprot',right_on='From').drop(columns = ['From'])

from Bio.SeqUtils.ProtParam import ProteinAnalysis
df['MW']=0
for index, row in df_prot.iterrows():
    prot = ProteinAnalysis(row['Sequence'])
    df_prot.loc[index,'MW'] =prot.molecular_weight()`


# followed by:
`if os.path.exists(CACHED_PROTEINS):
    df_prot = pd.read_csv(CACHED_PROTEINS, index_col=0, sep="\t")
    print('reading from protein cache...')
else:
#     df_prot = extract_proteins(model)
    df_prot.to_csv(CACHED_PROTEINS, sep="\t", index=False)
    
for i, row in df_prot.iterrows():
    if row['reactions'] in model.proteins:
        model.proteins.get_by_id(row['reactions']).mw = row['MW']`
```

**Comment by carrascomj** [comment]
I benchmarked the implementations and yours is faster (even for a small number of proteins, which should benefit my implementation) and accounts for the pagination that I wanted to use.

```
------------------------------------------------------------------------------------------- benchmark: 2 tests ------------------------------------------------------------------------------------------
Name (time in s)                                  Min               Max              Mean            StdDev            Median               IQR            Outliers     OPS            Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_extract_proteins_retrieves_all_mw         1.0035 (1.0)      1.1767 (1.0)      1.0431 (1.0)      0.0749 (1.0)      1.0118 (1.0)      0.0513 (1.0)           1;1  0.9587 (1.0)           5           1
test_extract_proteins_retrieves_all_mw_25b     1.0620 (1.06)     1.3465 (1.14)     1.1764 (1.13)     0.1140 (1.52)     1.1608 (1.15)     0.1715 (3.34)          2;0  0.8500 (0.89)          5           1
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

I'll commit your changes and let you know!

**Comment by carrascomj** [comment]
@cplong90 I added your code and tests are passing. I think the PR can be merged, let me know what you think!

**Comment by cplong90** [comment]
@carrascomj looks good, thanks!

**Pull request merged**
